### PR TITLE
Momentum merger and bug fixes

### LINKED ISSUE #166: Radius normalization issue
Beam radius sharply changes between the sections with different wavelengths

### PR DESCRIPTION
**Pull request by skutsaev**
- Hellweg now solves the momentum equations (gamma*beta), instead of velocity (beta)
- Fixed the bug with Bessel function series expansion -Fixed the bug when beam radius wasn't renormalized when frequency changes (or after the first drift tube element) -Fixed the bug with multiple sections
-Changed keyword "COULOMB" to "LAPOSTOLLE"

### CODE REVIEW

**Comment by bruhwiler** [comment]
The code is not compiling successfully on linux.
I need to further diagnose this and possibly request assistance from the software team.

**Comment by robnagler** [comment]
@bruhwiler do you want us to look at this?

**Comment by bruhwiler** [comment]
Yes, please.

**Comment by robnagler** [comment]
The last four PRs had failed the tests. I'm going to have to revert them all, and add them one by one.

**Comment by robnagler** [comment]
@skutsaev @ilyapogorelov This merge was a bit more complicated. Would both review the diffs of Beam.cpp and BeamSolver.cpp to make sure it's ok. Thanks

**Comment by ilyapogorelov** [comment]
Looks fine to me.

**Pull request merged**
