### PR TITLE
148 bug from the user

### LINKED ISSUE #148: Bug from the user
"Suddenly, I encountered some issues. But maybe you know the reason so I ask for your help. In particular, I simulated a 9.3 GHz TW buncher consisting of several cells. The first cell is beta=0.42 cell and the second cell is also beta=0.42 cell but the field of the second cell is 2.2 times higher than the field in the first cell (see the attached slide where you can see fragments of Hellweg's codes (right) and power distribution results (left). In the described example I see ~200 kW power drop between the first and the second cells. The total incident power is as high as 1.7 MW. If I simulate the first cell only, I do not see any unusual power behaviour."

### PR DESCRIPTION
**Pull request by skutsaev**

### CODE REVIEW

**Comment by bruhwiler** [comment]
On line 364 of BeamSolver.cpp there is a new use of the Embarcadero method ReadBool()

To compile on linux, we need to create an g++ compatible wrapper for this method.

@robnagler or @garsuga  -- could you assist?

**Comment by robnagler** [comment]
@garsuga lmk if you need help

**Comment by garsuga** [comment]
It builds now but it needs to be tested. I am not sure where ReadBool gets used, @bruhwiler can you see if it runs fine for you?

**Comment by garsuga** [comment]
The tests are failing now with something that seems unrelated to ReadBool

**Comment by garsuga** [comment]
@skutsaev I am going to hand this back to you to fix whatever is failing in the tests.

**Comment by skutsaev** [comment]
It compiles and runs on my computer fine

**Comment by robnagler** [comment]
@skutsaev this PR introduces [a malloc issue](https://github.com/radiasoft/rshellweg/actions/runs/4058679513/jobs/6985956097#step:3:153):

```txt

tests/pkcli/beam_solver_test.py::test_beam_solver malloc(): corrupted top size
Fatal Python error: Aborted

Current thread 0x00007fa272e87740 (most recent call first):
  File "/home/runner/work/rshellweg/rshellweg/rshellweg/solver.py", line 22 in solve
  File "/home/runner/work/rshellweg/rshellweg/tests/pkcli/beam_solver_test.py", line 24 in test_beam_solver
```

Can you think of a reason why this would be?

**Comment by skutsaev** [comment]
Maybe there is some incorrect array creation, which Embarcadero treats fine? I'll try to investigate, but it's not an easy check without more details.

**Comment by robnagler** [comment]
You can use our jupyter server to compile this. Visit sirepo.com/jupyter. Once logged in, start a terminal in JupyterLab then:

```sh
git clone https://github.com/radiasoft/rshellweg
cd rshellweg
pip install -e .
pykern test
```

If you need more help, let me know.

**Comment by skutsaev** [comment]
Unfortunately, python and Linux are beyond my expertise, so I will need to use embarcadero to look for the problem

**Comment by robnagler** [comment]
If you aren't getting the error in Embarcadero, we'll debug further.

**Comment by skutsaev** [comment]
I don’t, but when I tried to compile with CodeGuard enabled (the feature to locate memory leaks), it crashed. So there might be something. I’ll check when I get to the computer

**Review by bruhwiler — APPROVED** [review]
I went through the code with the originator of the PR and discussed.

**Pull request merged**
