### PR TITLE
20221114 fix #110: fix compile errors and add missing ansistring functions

### LINKED ISSUE #110: 20221005 Add filename functions or AnsiString support functions
image

### PR DESCRIPTION
**Pull request by garsuga**
merging this into kutsaev due to split git history. need to resolve conflicts with that branch to merge to master

### CODE REVIEW

**Comment by robnagler** [comment]
@garsuga how is this going?

**Comment by bruhwiler** [comment]
Reviewing the code, it looks fine to me.

> pip install -e .
and
> pip install .
both fail for me.

Therefore the tests fail, because they cannot import rslinac

@robnagler or @garsuga -- can you suggest a course of action?

**Comment by robnagler** [comment]
https://github.com/radiasoft/rslinac/pull/117 fixes setup.py. It wasn't a PR.

**Comment by bruhwiler** [comment]
I'll merge this PR, despite being told that it's not a PR.

**Comment by robnagler** [comment]
Don't merge anything, please.

**Comment by robnagler** [comment]
Each PR solves a different issue so we have to merge them in a specific order and a specific way.

**Comment by robnagler** [comment]
Fix #98 makefile deps

**Comment by garsuga** [comment]
I opened https://github.com/radiasoft/rslinac/tree/110-new-commits which includes these commits with the newest from kutsaev_2021b. Tests still succeed on that branch so I think everything should work after a merge

**Comment by robnagler** [comment]
Fixed with https://github.com/radiasoft/rslinac/pull/119

**Pull request closed without merging**
