### PR TITLE
133 examples directory

### LINKED ISSUE #133: create examples directory and cleanup docs

### PR DESCRIPTION
**Pull request by bruhwiler**
@ilyapogorelov -- please review this PR.

You should be able to run the test_01/ example.
The other examples don't run because they need additional files.

### CODE REVIEW

**Comment by ilyapogorelov** [comment]
Where should the run directory be in relation to the library? 
I'm getting module import error when running either from the examples/test_01/ directory or the directory where the build was done and where the pyhellweg.cpp and the build directory with .o's were created. 

The import errors are a bit more verbose when trying just the import in ipython:

rslinac$ cd examples/test_01/
test_01$ ipython
Python 3.7.2 (default, Jul 20 2022, 21:05:08) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.34.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from rshellweg.solver import BeamSolver
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-894d02f56d43> in <module>
----> 1 from rshellweg.solver import BeamSolver

ModuleNotFoundError: No module named 'rshellweg'

In [2]: exit()
test_01$ cd ../..
rslinac$ ipython
Python 3.7.2 (default, Jul 20 2022, 21:05:08) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.34.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from rshellweg.solver import BeamSolver
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-894d02f56d43> in <module>
----> 1 from rshellweg.solver import BeamSolver

~/jupyter/StaffScratch/ilyapogorelov/gcfour/workspace/01-eoms-for-momentum/rslinac/rshellweg/solver.py in <module>
      5 :license: http://www.apache.org/licenses/LICENSE-2.0.html
      6 """
----> 7 import rshellweg.pyhellweg
      8 
      9 

ModuleNotFoundError: No module named 'rshellweg.pyhellweg'

Do I need to update my PYTHONPATH, or there's some step I'm missing?

**Comment by bruhwiler** [comment]
Because the name of the repository has changed from rslinac to rshellweg, I recommend that you clone it again with the correct name. Then checkout the branch 133-examples-directory

At this point, from the top level directory, build the Hellweg library via
  > make

If the library builds without errors, then install it via
   > pip install -e .

Assuming that completes without errors, you can cd to ..../examples/test_01/

From there, you should be able to run the example via
    > python main.py

**Comment by bruhwiler** [comment]
@robnagler -- the python-ci tests are failing.  Could you please have a look?

**Comment by ilyapogorelov** [comment]
The code now runs. 
An unrelated (probably) issue is that the code produces an identical output distribution on every run, which doesn't make sense, given the rng-based initial distribution generation (if I understand this aspect of the code workings correctly).
Should I accept and close, or should I wait for Rob to take a look at the python-ci tests failing?

**Comment by bruhwiler** [comment]
A random distribution is always the same, unless the seed is randomized. That could be the explanation.

Let's wait for @robnagler or @garsuga to have a look at the failing tests.

**Comment by ilyapogorelov** [comment]
I believe it's the other way around: The distribution is/should be different every time (the rng seed being set e.g. by the clock) unless the seed is specified.  Specifying the seed is how you get different but reproducible quasi-random distributions.

**Comment by bruhwiler** [comment]
I think the problem is that the example input files are old and need to be updated.
I'm going to merge this PR and then we can get some working input files in place.

**Pull request merged**
